# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(625, 636)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        LoginWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelUsuario = QtWidgets.QLabel(self.centralwidget)
        self.labelUsuario.setGeometry(QtCore.QRect(60, 270, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.labelUsuario.setFont(font)
        self.labelUsuario.setStyleSheet("\n"
"\n"
"")
        self.labelUsuario.setObjectName("labelUsuario")
        self.lnputUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.lnputUsuario.setGeometry(QtCore.QRect(240, 280, 181, 31))
        self.lnputUsuario.setObjectName("lnputUsuario")
        self.InputContrasena = QtWidgets.QLineEdit(self.centralwidget)
        self.InputContrasena.setGeometry(QtCore.QRect(240, 340, 181, 31))
        self.InputContrasena.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 1,\n"
"        stop: 0 rgb(180, 220, 255),\n"
"        stop: 1 rgb(200, 255, 230)\n"
"    );\n"
"    font-family: \"Century Gothic\";\n"
"    font-size: 18px;\n"
"    padding: 8px 14px;\n"
"    border-radius: 14px;\n"
"}\n"
"")
        self.InputContrasena.setObjectName("InputContrasena")
        self.btnIngresar = QtWidgets.QPushButton(self.centralwidget)
        self.btnIngresar.setGeometry(QtCore.QRect(90, 430, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btnIngresar.setFont(font)
        self.btnIngresar.setStyleSheet("background-color: rgb(170, 183, 255);\n"
"\n"
"")
        self.btnIngresar.setObjectName("btnIngresar")
        self.lblmensaje = QtWidgets.QLabel(self.centralwidget)
        self.lblmensaje.setEnabled(True)
        self.lblmensaje.setGeometry(QtCore.QRect(220, 520, 171, 61))
        self.lblmensaje.setObjectName("lblmensaje")
        self.labelContrasena = QtWidgets.QLabel(self.centralwidget)
        self.labelContrasena.setGeometry(QtCore.QRect(20, 330, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.labelContrasena.setFont(font)
        self.labelContrasena.setStyleSheet("")
        self.labelContrasena.setObjectName("labelContrasena")
        self.lbllogo = QtWidgets.QLabel(self.centralwidget)
        self.lbllogo.setGeometry(QtCore.QRect(130, 30, 361, 181))
        self.lbllogo.setText("")
        self.lbllogo.setPixmap(QtGui.QPixmap("LogoBiomodal_MSJS.jpg"))
        self.lbllogo.setScaledContents(True)
        self.lbllogo.setObjectName("lbllogo")
        self.btnSalir = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalir.setGeometry(QtCore.QRect(340, 430, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btnSalir.setFont(font)
        self.btnSalir.setStyleSheet("background-color: rgb(170, 183, 255);")
        self.btnSalir.setObjectName("btnSalir")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 625, 26))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Login"))
        self.labelUsuario.setText(_translate("LoginWindow", "Usuario"))
        self.btnIngresar.setText(_translate("LoginWindow", "Ingresar"))
        self.lblmensaje.setText(_translate("LoginWindow", "\"Usuario incorrecto\""))
        self.labelContrasena.setText(_translate("LoginWindow", "Contraseña"))
        self.btnSalir.setText(_translate("LoginWindow", "SALIR"))
