# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Captura.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 304)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 90, 401, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(-20, 200, 441, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lblCamara = QtWidgets.QLabel(Dialog)
        self.lblCamara.setGeometry(QtCore.QRect(130, 40, 131, 16))
        self.lblCamara.setObjectName("lblCamara")
        self.btnCapturar = QtWidgets.QPushButton(Dialog)
        self.btnCapturar.setGeometry(QtCore.QRect(20, 140, 93, 28))
        self.btnCapturar.setObjectName("btnCapturar")
        self.btnGuardarTemporal = QtWidgets.QPushButton(Dialog)
        self.btnGuardarTemporal.setGeometry(QtCore.QRect(230, 140, 131, 28))
        self.btnGuardarTemporal.setObjectName("btnGuardarTemporal")
        self.lblImagenCapturada = QtWidgets.QLabel(Dialog)
        self.lblImagenCapturada.setGeometry(QtCore.QRect(140, 250, 141, 16))
        self.lblImagenCapturada.setObjectName("lblImagenCapturada")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblCamara.setText(_translate("Dialog", "STREAM DE CAMARA"))
        self.btnCapturar.setText(_translate("Dialog", "Capturar"))
        self.btnGuardarTemporal.setText(_translate("Dialog", "Guardar Temporal"))
        self.lblImagenCapturada.setText(_translate("Dialog", "IMAGEN CAPTURADA"))
