# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(339, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameMenu = QtWidgets.QFrame(self.centralwidget)
        self.frameMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMenu.setObjectName("frameMenu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameMenu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnImagenes = QtWidgets.QPushButton(self.frameMenu)
        self.btnImagenes.setObjectName("btnImagenes")
        self.verticalLayout.addWidget(self.btnImagenes)
        self.btnSenales = QtWidgets.QPushButton(self.frameMenu)
        self.btnSenales.setProperty("style", "")
        self.btnSenales.setObjectName("btnSenales")
        self.verticalLayout.addWidget(self.btnSenales)
        self.btnCSV = QtWidgets.QPushButton(self.frameMenu)
        self.btnCSV.setObjectName("btnCSV")
        self.verticalLayout.addWidget(self.btnCSV)
        self.btnCapturar = QtWidgets.QPushButton(self.frameMenu)
        self.btnCapturar.setObjectName("btnCapturar")
        self.verticalLayout.addWidget(self.btnCapturar)
        self.btnHistorial = QtWidgets.QPushButton(self.frameMenu)
        self.btnHistorial.setObjectName("btnHistorial")
        self.verticalLayout.addWidget(self.btnHistorial)
        self.btnCerrarSesion = QtWidgets.QPushButton(self.frameMenu)
        self.btnCerrarSesion.setObjectName("btnCerrarSesion")
        self.verticalLayout.addWidget(self.btnCerrarSesion)
        self.horizontalLayout.addWidget(self.frameMenu)
        self.frameContenido = QtWidgets.QFrame(self.centralwidget)
        self.frameContenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameContenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameContenido.setObjectName("frameContenido")
        self.labelTituloDashboard = QtWidgets.QLabel(self.frameContenido)
        self.labelTituloDashboard.setGeometry(QtCore.QRect(140, 10, 131, 21))
        self.labelTituloDashboard.setObjectName("labelTituloDashboard")
        self.stackprincipal = QtWidgets.QStackedWidget(self.frameContenido)
        self.stackprincipal.setGeometry(QtCore.QRect(40, 60, 301, 471))
        self.stackprincipal.setObjectName("stackprincipal")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackprincipal.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackprincipal.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.frameContenido)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 339, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackprincipal.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnImagenes.setText(_translate("MainWindow", "Imagenes"))
        self.btnSenales.setText(_translate("MainWindow", "Señales"))
        self.btnCSV.setText(_translate("MainWindow", "CSV"))
        self.btnCapturar.setText(_translate("MainWindow", "Capturar Imagen"))
        self.btnHistorial.setText(_translate("MainWindow", "Historial"))
        self.btnCerrarSesion.setText(_translate("MainWindow", "Cerrar Sesión"))
        self.labelTituloDashboard.setText(_translate("MainWindow", "Stack de Vistas"))
